/*
* This header is generated by classdump-dyld 1.0
* on Sunday, November 10, 2019 at 11:10:53 PM Eastern European Standard Time
* Operating System: Version 13.1.3 (Build 17A878)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSArray, NSDictionary, NSMutableDictionary;

@interface PSSpecifier : NSObject +(id)emptyGroupSpecifier;
+(id)groupSpecifierWithName:(id)arg1 ;
+(id)preferenceSpecifierNamed:(id)arg1 target:(id)arg2 set:(SEL)arg3 get:(SEL)arg4 detail:(Class)arg5 cell:(long long)arg6 edit:(Class)arg7 ;
+(id)groupSpecifierWithID:(id)arg1 ;
+(id)groupSpecifierWithID:(id)arg1 name:(id)arg2 ;
+(id)specifierWithSpecifier:(id)arg1 ;
+(long long)autoCorrectionTypeForNumber:(id)arg1 ;
+(long long)autoCapsTypeForString:(id)arg1 ;
+(long long)keyboardTypeForString:(id)arg1 ;
+(id)deleteButtonSpecifierWithName:(id)arg1 target:(id)arg2 action:(SEL)arg3 ;
-(id)init;
-(id)description;
-(NSString *)name;
-(id)userInfo;
-(id)propertyForKey:(id)arg1 ;
-(void)setProperty:(id)arg1 forKey:(id)arg2 ;
-(void)setValues:(NSArray *)arg1 ;
-(NSArray *)values;
-(id)objectForKeyedSubscript:(id)arg1 ;
-(void)setTarget:(id)arg1 ;
-(id)target;
-(void)setName:(NSString *)arg1 ;
-(NSString *)identifier;
-(void)setObject:(id)arg1 forKeyedSubscript:(id)arg2 ;
-(void)setIdentifier:(NSString *)arg1 ;
-(void)setUserInfo:(id)arg1 ;
-(void)removePropertyForKey:(id)arg1 ;
-(id)properties;
-(void)setProperties:(id)arg1 ;
-(void)setButtonAction:(SEL)arg1 ;
-(SEL)buttonAction;
-(long long)cellType;
-(void)setCellType:(long long)arg1 ;
-(void)setValues:(id)arg1 titles:(id)arg2 ;
-(void)setKeyboardType:(long long)arg1 autoCaps:(long long)arg2 autoCorrection:(long long)arg3 ;
-(BOOL)showContentString;
-(void)performLegacyAction;
-(SEL)controllerLoadAction;
-(void)performControllerLoadAction;
-(void)performButtonAction;
-(SEL)confirmationAction;
-(void)performConfirmationAction;
-(SEL)confirmationAlternateAction;
-(void)performConfirmationAlternateAction;
-(SEL)confirmationCancelAction;
-(void)performConfirmationCancelAction;
-(SEL)legacyCancel;
-(void)setLegacyAction:(SEL)arg1 ;
-(void)setControllerLoadAction:(SEL)arg1 ;
-(SEL)legacyAction;
-(void)setupIconImageWithPath:(id)arg1 ;
-(Class)detailControllerClass;
-(void)setDetailControllerClass:(Class)arg1 ;
-(Class)editPaneClass;
-(void)setEditPaneClass:(Class)arg1 ;
-(void)setLegacyCancel:(SEL)arg1 ;
-(void)setConfirmationAction:(SEL)arg1 ;
-(void)setConfirmationAlternateAction:(SEL)arg1 ;
-(void)setConfirmationCancelAction:(SEL)arg1 ;
-(void)setShowContentString:(BOOL)arg1 ;
-(NSDictionary *)titleDictionary;
-(void)setTitleDictionary:(NSDictionary *)arg1 ;
-(NSDictionary *)shortTitleDictionary;
-(void)setShortTitleDictionary:(NSDictionary *)arg1 ;
-(BOOL)hasValidSetter;
-(BOOL)hasValidGetter;
-(void)setValues:(id)arg1 titles:(id)arg2 shortTitles:(id)arg3 ;
-(id)initWithName:(id)arg1 target:(id)arg2 set:(SEL)arg3 get:(SEL)arg4 detail:(Class)arg5 cell:(long long)arg6 edit:(Class)arg7 ;
-(void)performSetterWithValue:(id)arg1 ;
-(id)performGetter;
-(void)loadValuesAndTitlesFromDataSource;
-(void)setValues:(id)arg1 titles:(id)arg2 shortTitles:(id)arg3 usingLocalizedTitleSorting:(BOOL)arg4 ;
-(void)setupIconImageWithBundle:(id)arg1 ;
-(long long)titleCompare:(id)arg1 ;
-(BOOL)isEqualToSpecifier:(id)arg1 ;
-(id)weakUserInfo;
-(void)setWeakUserInfo:(id)arg1 ;
@end

